name: ventipro
description: "20PRO"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_messaging: ^14.7.21
  flutter_spinkit: ^5.2.1
  device_info_plus: ^10.1.2
  openapi_generator_annotations: 4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  openapi_generator: 4.13.1
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/