name: ventipro
description: "20PRO"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_messaging: ^14.7.21
  device_info_plus: ^10.1.2
  openapi_generator_annotations: 4.13.1
  provider: ^6.1.2
  vibration: ^2.0.1
  fluttertoast: ^8.2.8
  flutter_localization: ^0.2.1
  badges: ^3.1.2
  flutter_local_notifications: ^18.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  lottie: ^3.1.0
  excel: ^4.0.3
  share_plus: ^7.2.2
  syncfusion_flutter_xlsio: ^25.2.3
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1
  platform_device_id: ^1.0.1
  font_awesome_flutter: ^10.8.0
  persistent_bottom_nav_bar: ^6.2.1
  audioplayers: ^6.1.0
  awesome_bottom_bar: ^1.2.4

  
dev_dependencies:

  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  openapi_generator: 4.13.1
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/sounds/