// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtBhYehGZkp10sL2hFzNJz-yivRlgBZ0',
    appId: '1:54799761759:web:1addd085c90b5d715276ea',
    messagingSenderId: '54799761759',
    projectId: 'pro-11ac5',
    authDomain: 'pro-11ac5.firebaseapp.com',
    storageBucket: 'pro-11ac5.firebasestorage.app',
    measurementId: 'G-JJ3EGRPTZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-1wAjgeKjBrCHF8-39ulBf4QeZwj0y-0',
    appId: '1:54799761759:android:9c6d819633a8cd075276ea',
    messagingSenderId: '54799761759',
    projectId: 'pro-11ac5',
    storageBucket: 'pro-11ac5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbreUIKfZAKdl6jQ1F7QLN53Jt2D1ZL0w',
    appId: '1:54799761759:ios:477f4e279ae1da895276ea',
    messagingSenderId: '54799761759',
    projectId: 'pro-11ac5',
    storageBucket: 'pro-11ac5.firebasestorage.app',
    iosBundleId: 'com.ventipro.app.20pro',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbreUIKfZAKdl6jQ1F7QLN53Jt2D1ZL0w',
    appId: '1:54799761759:ios:477f4e279ae1da895276ea',
    messagingSenderId: '54799761759',
    projectId: 'pro-11ac5',
    storageBucket: 'pro-11ac5.firebasestorage.app',
    iosBundleId: 'com.ventipro.app.20pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbreUIKfZAKdl6jQ1F7QLN53Jt2D1ZL0w',
    appId: '1:54799761759:ios:d555f1921b6d273d5276ea',
    messagingSenderId: '54799761759',
    projectId: 'pro-11ac5',
    storageBucket: 'pro-11ac5.firebasestorage.app',
    iosBundleId: 'com.ventipro.app.20pro.RunnerTests',
  );
}
